# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Personal Homepage for Chunjiang Zhu
tagline:          'A Jekyll theme'
description:      'This is a web page for Chunjiang Zhu'
url:              chunjiangzhu.github.io
baseurl:          http://chunjiangzhu.github.io/chunjiangzhu/

author:
  name:           'Chunjiang Zhu'
  url:            https://twitter.com/chunjiangzhu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chunjiangzhu/chunjiangzhu.github.io
